{% set name = "pytest-cpp" %}
{% set version = "0.4.1" %}
{% set sha256 = "affa4d5f576def8fdb47f079ddcb45c79befa854f530757749210e83f84b242d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytest

test:
  imports:
    - pytest_cpp

about:
  home: http://github.com/pytest-dev/pytest-cpp
  license: MIT
  license_file: LICENSE
  summary: "Use pytest's runner to discover and execute C++ tests"

extra:
  recipe-maintainers:
    - gqmelo
    - nicoddemus
