travis:
  secure:
    BINSTAR_TOKEN: SN6jQJ6haVY2LK43MpTJ5ZMBfIYHbtq+OEdAeRL57XytS3LL6svhofKbYs/0vg8Nwdy4pt3WDEBNr4Pfzx/RkhBEqQp9G3x2utm1WpiXhTbxEjUoeQlttGFRPJYry8/0YLeKmAz8LB32GG7lVfNHISIMsB/anAFGgcPRWUuJkI42CyPa91Ppjdh5LEI35Bj6f7PZVE0Dj7leKw3R7EgrxT3++gLpuLNe6/RHWNnxxK6W1ivEVbT6/LD55eXZtu5hCAEEm3i98/8cD+8ZkWgTbTiSAIubQ60oGRupFEtaLRDqKS+8p45crTw/HGpGuPSs81Q8STKcXdIEHXQ50E8DNhwjfJlTazrTpobz0x/391SBo+Utkp9vNPAuQreZ1qGl9CmEi0TFrS5f004tQMax1deeyCNE/JYOQSE/RsJBgxZRzNwzjGykONvRjAdfGgfrEGRsoG0LRI1UnHbPLpVn1+JFZZ7HVpvwCLRVhPzXA69vbOc5ecVrQk0HqGLwN3IdFzS+9nEHXKNuBpKmyguQa0KjPN4MvOG0NcooVaaGrDjRNMcZAhsuycEisfDrz5CrY6SvbfhlT50e2QtwO6ST9Pg7KCYSRe0ILVH6FDfTtvU3YprGGhOB7NYUIoXI7e+px8KeZ4nmEarSWRWbMNJ9qdqZH2nljHDBvY8mIlBkUcM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
